# Generated by Django 6.0.6 on 2026-07-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tax_rate',
            field=models.PositiveIntegerField(choices=[(0, '0% - Essential/Exempt goods'), (5, '5% - Daily essentials, groceries, medicines'), (18, '18% - Standard rate (electronics, clothing, most goods)'), (40, '40% - Luxury/sin goods')], default=18),
        ),
    ]
