# Generated by Django 6.0.6 on 2026-07-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_category_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tax_rate_applied',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
