# Generated by Django 6.0.6 on 2026-07-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_coupon_invoice_coupon_code_invoice_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
