# Generated by Django 6.0.6 on 2026-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_shipping_charge_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='same_as_billing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
